[build]
  publish = "."
  functions = "src/netlify/functions"

[functions]
  node_bundler = "esbuild"
  directory = "src/netlify/functions"
  included_files = ["src/*.txt", "src/netlify/functions/*.md"]
  external_node_modules = ["@anthropic-ai/sdk", "openai"]


[dev]
  functionsPort = 8888
