-- Register the ten SHAREME sharing codes.
--
-- Generated by scripts/create-share-codes.sh on 2026-08-21 and pasted here so the ids are
-- recorded in the repo rather than only in a terminal that has since scrolled away.
--
-- WHAT THESE ARE: ten separate handles on ONE 15% coupon (3oqx0N2l), meant to be handed to
-- affiliates to pass along. Ten codes rather than one because purchase_sources records
-- which code a sale came through — so ten handles on a single discount is what makes it
-- possible to tell whose sharing worked, without minting a different discount per person.
--
-- Each is capped at 50 redemptions and expires 30 Sep 2026. Both bounds exist because a
-- code anyone may share is a code that can leak to a coupon site; without them a leak is an
-- open-ended 15% offer.
--
-- first_time_transaction is set in Stripe, so each is restricted to customers with no prior
-- successful payment. Note what that actually checks — a Stripe CUSTOMER with no prior
-- payment. A returning buyer checking out under a different email is a new customer to
-- Stripe and passes. Together with this app's one-discount-per-account rule that is enough
-- friction for an acquisition offer; it is not a fraud control.
--
-- ── THE COUPON BEHIND THEM ───────────────────────────────────────────────────
--
-- 3oqx0N2l — 15% off, duration ONCE, redeem_by 2026-10-01T05:59:59Z.
--
-- It replaced DSkGhpCJ, which was duration FOREVER: that one would have taken 15% off every
-- renewal for the life of the subscription, not just the first purchase. Nobody had redeemed
-- it (times_redeemed was 0), so the swap cost nothing. DSkGhpCJ also carried a redeem_by of
-- 2026-08-21, hours away when this was written, and a coupon's redeem_by cannot be changed
-- after creation — Stripe only allows updating name, metadata and currency_options. Hence a
-- new coupon rather than an extended one.
--
-- A promotion code may not outlive its coupon. The codes below expire one minute before the
-- coupon's redeem_by for that reason; if you mint more on this coupon, stay under it.

insert into public.affiliate_codes (code, stripe_promotion_code_id, discount_label, active, expires_at)
values
  ('SHAREMETFHTJ', 'promo_1U72eqBgBMKG03Ip8KTlBNcg', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMECAP3Y', 'promo_1U72eqBgBMKG03Ip7VmIPYEj', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMECRQKQ', 'promo_1U72eqBgBMKG03IpFkaHkKcM', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMEJ2PR3', 'promo_1U72erBgBMKG03Ipa6yqsAwJ', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMEM6Q9A', 'promo_1U72erBgBMKG03IpJ5uGeqHa', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREME2AFGK', 'promo_1U72erBgBMKG03IpyPDFB6Bd', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMEDQAD2', 'promo_1U72esBgBMKG03IpXH430g5W', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMEK4KQM', 'promo_1U72esBgBMKG03IpNG9yl8B5', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMEJP96W', 'promo_1U72esBgBMKG03Ip4aiL95OW', '15% off', true, '2026-10-01T05:59:00Z'),
  ('SHAREMEGJ6X6', 'promo_1U72esBgBMKG03IpcbVQUEI2', '15% off', true, '2026-10-01T05:59:00Z')

on conflict (code) do update
  set stripe_promotion_code_id = excluded.stripe_promotion_code_id,
      discount_label           = excluded.discount_label,
      active                   = excluded.active,
      expires_at               = excluded.expires_at;

-- expires_at is set here as well as in Stripe, deliberately. Stripe wins at checkout, so a
-- code this table still considers live but Stripe has expired produces a Stripe error after
-- the buyer has committed. Expiring in both places means the buyer is turned away here
-- first, with this app's own message.
--
-- owner_user_id is null on all ten: they are sharing handles, not codes issued to a named
-- person. Set it on a code you give to a specific affiliate — that is what makes
-- self-referral detection meaningful, since resolveReferralCode compares the buyer's id to
-- it and flags a match rather than letting someone quietly discount their own purchase.
-- Until then, attribution is by code string via purchase_sources.

-- Verify — expect ten rows, all active, all 2026-10-01:
select code, stripe_promotion_code_id, discount_label, active, expires_at
from public.affiliate_codes
where code like 'SHAREME%'
order by code;
